framework:
    mailer:
        dsn: 'smtp://smtp.gmail.com:587?encryption=tls&auth_mode=login&username=aliounedia2010@gmail.com&password=jivenqanwjxzthxz'
        envelope:
            sender: 'aliounedia2010@gmail.com'
       